- hosts: web
  tasks:
  - name: Install Apache
    yum:
      name: httpd
      state: latest

  - name: Download file and force basic auth
    get_url:
      url: http://example.com/path/file.conf
      dest: /etc/foo.conf
      force_basic_auth: yes

